services:
  - type: web
    name: makjicolor
    env: python
    region: frankfurt        # ou oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: WHATSAPP_NUMBER
        sync: false